keystore: 
  path: "local.jks"
  password: "![xKUgIUxIUOSQfD82up5YWA==]" # Please encrypt it with the encryption key being used in the project. "PASSWORD" is the current default key

security:
  basic:
    username: "tod_user"
    password: "![p/5rrykUfGI=]" # Please encrypt it with the encryption key being used in the project. "PASSWORD" is the template encryption password

https:
  port: "8089" # This value is mostly default, only change if you have any other specific port to be used.
  basepath: "api/v1"
  connection:
    timeout: "60000" # In Milliseconds
  reconnection:
    frequency: "60000" # In Milliseconds
    attempts: "5"
  
logging:
  timeFormat: "yyyy-MM-dd'T'HH:mm:ss"
  timeZone: "America/Vancouver"

feature:
  account-sync: "true"
  process-B: "true"


db.sapi:
  host: "localhost"
  port: "8083"
  basepath: "api/v1"
  path:
    users: "users"
    delta: "delta"
    health: "heartbeat"
  auth:
    username: "tod_user"
    password: "![p/5rrykUfGI=]"
  reconnection:
    frequency: "60000"
    attempts: "5"
  timeout:
    connection: "600000"
    idle: "60000"
    
watermark:
  default:
    account-sync: "2022-01-10 00:00:00.000000"

salesforce.sapi:
  host: "localhost"
  port: "8082"
  basepath: "api/v1"
  path:
    account: "Account"
    health: "health"
  auth:
    username: "tod_user"
    password: "![p/5rrykUfGI=]"
  reconnection:
    frequency: "60000"
    attempts: "5"
  timeout:
    connection: "60000"
    idle: "5"
  
cloudhub:
  username: "xxxx"
  password: "XXX"
  environment: "xxxx"
  domain: "xxxx"
  environmentId: "xxxx"
  reconnection:
    frequency: "60000"
    attempts: "5"
  notification:
    timestamp:
      timezone: "America/Vancouver"
      format: "KK:mm:ss a, MMMM dd, uuuu"
